CREATE TABLE IF NOT EXISTS characters (id TEXT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS world_state (id INT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, kind TEXT, data JSONB NOT NULL, created_tick INT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY, character_id TEXT NOT NULL, kind TEXT, text TEXT, importance FLOAT, tags JSONB, data JSONB, created_tick INT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS job_listings (id TEXT PRIMARY KEY, profession_id TEXT, data JSONB NOT NULL, open BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS news_items (id TEXT PRIMARY KEY, data JSONB NOT NULL, created_tick INT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public_figures (id TEXT PRIMARY KEY, data JSONB NOT NULL);
